### ISSUE TITLE
gbb 的目的是什么

### ISSUE THREAD

**Issue by linuxr** [voidint/gbb#2]
刚看到这个工具，之前我也遇到过类似的问题，我在 idcos/cloudcli 中用 makefile 的方式来处理的。
其实就是改下默认的编译命令，编译时动态赋值变量，比如（编译是加入当前的 revision number）：

**gb build -ldflags "-X main.build=`git rev-parse HEAD`"**

golang 中 gb 这个工具的目的是管理golang 的工程，还可以安装，卸载，升级第三方包等。
gbb 这个工具的目的是类似的，还是只是为了编译。如果只是编译，其实可以用 

alias gbb='gb build -ldflags "-X main.build=`git rev-parse HEAD`"'  之类的一行脚本就行。

**Comment by voidint** [comment]
gbb的目的是什么？要达到的目标，就如你所说的`编译时动态赋值变量`，当前最看重的就是`编译时间`和`git commit id`。

gbb中使用了什么高深技术来达到这个目的吗？没有，你上面已经给出了答案。`gbb --debug`也能够看到底层对应调用了什么命令。

那么，为什么不用shell脚本，甚至每次编译时不厌其烦地输入一长串的参数？撇开偏好的原因（手里拿把锤子，眼里看见的都是钉子），主要是觉得`这样更方便`（当然，方不方便其实也会因人而异）。怎么个方便法？
- 提供了人性化的`gbb init`工具，只需要几步就能生成项目的`编译信息配置文件gbb.json`。`gbb.json`里包含许多编译要用到的信息。这些信息在项目初建时搜集一次，今后就无需过多关注了，有点`一劳永逸`的意思。除非有大的调整，比如编译工具从`go install`变成了`gb build`。这都属于低频操作，谈不上成本。
- gbb.json中对那些`占位符`（其实就是变量，比如`编译时间`变量）并没有硬编码。变量名今天可以叫`Date`，明天可以叫`Time`，今天可以有2个占位符变量，明天可以再增加2个占位符变量，所有的这些没有硬编码，并且修改的成本很低，`gbb init`一次搞定。
- 编译时也很方便，随便`gbb`就能编译完成，如果要看底层调用的命令参数，那么`gbb --debug`来帮你。

**Comment by linuxr** [comment]
是个人偏好原因，喜欢就好  :)

**Comment by voidint** [comment]
补充两条：
- 跨平台
- 非全局生效，拥有天然的作用域，`gbb.json`配置仅在当前项目生效。这样就能做到在A项目调用`gb`编译，在B项目调用`go build/install`编译。

**Comment by linuxr** [comment]
:+1:  项目根目录放个脚本或者 makefile 也能达到一样的效果

**Comment by linuxr** [comment]
但是脚本要加入一些工程管理方面的东西就困难了

**Comment by voidint** [comment]
老司机 教教我 😄
